### ISSUE TITLE
use the same block deltaCoverageReport as given in document but get the error

### ISSUE THREAD

**Issue by shubhampanchal21109** [SurpSG/delta-coverage-plugin#28]
**Describe the Issue**

- we use the same block deltaCoverageReport as given in document but get the error

**Desktop (complete the following information):**
 - OS: [Windows 11]
 - Gradle version: [7.5.1]
 - Delta Coverage plugin version [1.0.0, 1.1.1, 1.2.0]

**Configuration Of Groovy Script**

- Below I mentioned the configuration of Groovy script.

```
deltaCoverageReport {
    diffSource.file = file('D:/service/patch.diff') 

    violationRules.failIfCoverageLessThan 0.9d

    reports {
        html.set(true)
    }
}
```

**Errors**

- It throws an error like this - 

> Cannot set readonly property: file for class: io.github.surpsg.deltacoverage.gradle.DiffSourceConfiguration

**Expected behavior**

- It should compute code coverage of new/modified code based on a provided diff

**Comment by SurpSG** [comment]
@shubhampanchal21109 
It's incorrect info in the readme.

use the next syntax:
```groovy
deltaCoverageReport {
    diffSource.file.set(file('D:/service/patch.diff'))
```

**Comment by shubhampanchal21109** [comment]
@SurpSG ,

It throws error like

> Cannot set the value of a property of type java.lang.String using an instance of type java.io.File.

**Comment by SurpSG** [comment]
my bad, it's string property, not file.

So, just update the configuration:
```groovy
deltaCoverageReport {
    diffSource.file.set('D:/service/patch.diff')
```

**Comment by shubhampanchal21109** [comment]
Hello,
Please provide an example for Groovy Script. In repo only Kotlin example configuration given.

**Comment by shubhampanchal21109** [comment]
> Hello, Provide an example for Groovy Script. In the repo, only the Kotlin example configuration is given. Please convert this example to Groovy
> 
> ```
> configure<io.github.surpsg.deltacoverage.gradle.DeltaCoverageConfiguration> {
>     diffSource { // Required. Only one of `file`, `url` or git must be spesified
>         //  Path to diff file 
>         file.set(file("path/to/file.diff")) 
>         
>         // URL to retrieve diff by
>         url.set("http://domain.com/file.diff") 
>         
>         // Compares current HEAD and all uncommited with provided branch, revision or tag 
>         git.compareWith.set("refs/remotes/origin/develop")
>     }
> 
>     // Required. By default exec files are taken from jacocoTestReport configuration if any
>     jacocoExecFiles = files("/path/to/jacoco/exec/file.exec")
>     // Required. By default sources are taken from jacocoTestReport configuration if any
>     srcDirs = files("/path/to/sources")
>     // Required. By default classes are taken from jacocoTestReport configuration if any
>     classesDirs = files("/path/to/compiled/classes")
> 
>     excludeClasses.value(listOf[ // Optional. Excludes classes from coverage report by set of patterns 
>             "*/com/package/ExcludeClass.class", // Excludes class "com.package.ExcludeClass"
>             "**/com/package/**/ExcludeClass.class", // Excludes classes like "com.package.ExcludeClass", "com.package.sub1.sub2.ExcludeClass", etc.
>             "**/ExcludeClass$NestedClass.class", // Excludes nested class(es) "<any-package>.ExcludeClass.NestedClass"
>             "**/com/package/exclude/**/*.*" // Excludes all in package "com.package.exclude"
>             // See more info about pattern rules: https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/util/PatternFilterable.html
>     ])
> 
>     reports {
>         html.set(true) // Optional. default `false`
>         xml.set(true) // Optional. default `false`
>         csv.set(true) // Optional. default `false`
>         reportDir.set("dir/to/store/reports") // Optional. Default 'build/reports/jacoco/deltaCoverage'
>     }
> 
>     // If violation rules are not configured, then no violations will be checked.
>     violationRules {
>         failOnViolation.set(true) // Optional. Default `false`. If `true` then task will fail if any violation is found.
> 
>         // [Option 1]---------------------------------------------------------------------------------------------------
>         // Optional. The function sets min coverage ration for instructions, branches and lines to '0.9'. 
>         // Sets failOnViolation to 'true'.
>         failIfCoverageLessThan(0.9d)
> 
>         // [Option 2]---------------------------------------------------------------------------------------------------
>         rule(io.github.surpsg.deltacoverage.gradle.CoverageEntity.INSTRUCTION) {
>             // Optional. If coverage ration is set then the plugin will check coverage ratio for this entity.
>             minCoverageRatio.set(0.9d)
>             // Optional. Disabled by default. The plugin ignores violation if the entity count is less than the threshold.
>             entityCountThreshold.set(1234)
>         }
>         rule(io.github.surpsg.deltacoverage.gradle.CoverageEntity.LINE) {
>             // ...
>         }
>         rule(io.github.surpsg.deltacoverage.gradle.CoverageEntity.BRANCH) {
>             // ...
>         }
> 
>         // [Option 3]---------------------------------------------------------------------------------------------------
>         // [.kts only] Alternative way to set violation rule.
>         io.github.surpsg.deltacoverage.gradle.CoverageEntity.BRANCH {
>             minCoverageRatio.set(0.7d)
>             entityCountThreshold.set(890)
>         }
> 
>         // [Option 4]---------------------------------------------------------------------------------------------------
>         // Sets violation rule for all entities: LINE, BRANCH, INSTRUCTION
>         all {
>             minCoverageRatio.set(0.7d)
>             entityCountThreshold.set(890)
>         }
>     }
> }
> ```

@SurpSG  I need groovy configuration for parameter description given for kotlin

**Comment by shubhampanchal21109** [comment]
Hi

We added configuration for git as below

**Comment by SurpSG** [comment]
Hi @shubhampanchal21109 

Here example how to configure git source: https://github.com/SurpSG/delta-coverage-plugin/blob/main/delta-coverage/src/functionalTest/kotlin/io/github/surpsg/deltacoverage/gradle/DeltaCoverageDiffSourcesTest.kt#L92

There are multiple [functional tests](https://github.com/SurpSG/delta-coverage-plugin/tree/main/delta-coverage/src/functionalTest/kotlin/io/github/surpsg/deltacoverage/gradle) that use real plugin configuration on groovy.

Seems, I should repeat configuration examples using groovy in README

**Comment by shubhampanchal21109** [comment]
Hi @SurpSG ,
Can we get just changed code, newly added code, or modified code coverage, not whole code base just changed code in commit or PR? If yes, then can you please provide Groovy conf for Gradle?

**Comment by SurpSG** [comment]
Hi @shubhampanchal21109 

Yes, this plugin is created exactly for building of code coverage report for modified or new code.

----

Here project example using groovy: https://github.com/SurpSG/delta-coverage-gradle-sample

How to test:
1. clone the project
2. checkout branch `delta-coverage-gradle-sample`
3. run tests to collect code coverage: `./gradlew test`
4. run delta coverage task to build delta coverage report: `./gradlew deltaCoverage`
5. open report and observe the results `build/reports/jacoco/deltaCoverage/html/index.html`

----

Note: 
```groovy
deltaCoverageReport {
    diffSource.git.compareWith('refs/remotes/origin/main')
}
```
This configuration tells to the plugin to generate diff between `delta-coverage-gradle-sample` and `main` branches. So, the generated diff is used to build delta coverage report.

----

If you have more questions then feel free to ask.

**Comment by shubhampanchal21109** [comment]
it works with the given config
