### ISSUE TITLE
'deltaCoverageReport.jacocoExecFiles' is not configured.

### ISSUE THREAD

**Issue by anandpurushottam** [SurpSG/delta-coverage-plugin#31]
**Describe the bug**
    id "io.github.surpsg.delta-coverage" version "1.3.0"
    
deltaCoverageReport {
    diffSource.git.compareWith 'HEAD'
    violationRules.failIfCoverageLessThan 0.1d
}

tried running  ./gradlew deltaCoverage

error:

> Task :pay-psp-ui-sdk:deltaCoverage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pay-psp-ui-sdk:deltaCoverage'.
> 'deltaCoverageReport.jacocoExecFiles' is not configured.

Please help with how to configure jacocoExecFiles in Grovy

**Comment by SurpSG** [comment]
Hi @anandpurushottam 

`Delta-coverage` requires three components:
- pathes to compiled classes dir(`.class` files)
- `.exec` files generated by `jacoco` during tests run
- pathes to code sources(if html report is enabled)

If `.exec` files are missed then the plugin fails build.

----

`Delta-coverage` plugin automatically applies `jacoco` plugin to project. 
Then `Delta-coverage` tries to autoconfigure itself from `jacoco` plugin defaults.

----

Probable  issues:
- `jacoco` was not applied - if you have non-standard project layout
- `jacoco` was applied successfully but `delta-coverage` wasn't able to autoconfigure itself from `jacoco`

----

For further investigation please check that `jacoco` plugin does it's job:
1. Check `jacocoTestReport` task is exist: 
    ```bash
    ./gradlew jacocoTestReport -m
    ```
2. Check that jacoco collects code coverage:
```bash
./gradlew test
``` 
Then check that file exist:
- `build/jacoco/test.exec`

Please, complete these steps and reply to me about the results.

**Comment by anandpurushottam** [comment]
Made some changes in the jacoco setup

With the changes, both XML and HTML reports are now generated using deltaCoverage

However, the generated report currently displays coverage information for all methods in the class.
The expected behavior is for the report to focus only on line changes, not the entire class.

**Below is the module level gradle configuration** 

https://gist.github.com/anandpurushottam/f2884759912262b62e78ec5e5d5d478a


The only code change is the addition of 
sum function rest you can ignore

Although it detects changes in another part of the file as well

**Here is the XML report**
https://gist.github.com/anandpurushottam/bf5a7f91c7199b90867e1d75bb84b251

Please help with this issue.

**Comment by SurpSG** [comment]
Hi @anandpurushottam 

could you please provide debug logs filtered by `io.github.surpsg.deltacoverage`?

```bash
./gradlew deltaCoverage -d | grep 'io.github.surpsg.deltacoverage'
```

**Comment by anandpurushottam** [comment]
@SurpSG 

https://gist.github.com/anandpurushottam/1949ff945999df9258d869bfa2b0112b

**Comment by SurpSG** [comment]
@anandpurushottam 

I've investigated the data you provided and haven't found any issues there.
Seems, we have some issue with filtering. 

----

Is there any reason why you using jacoco version `0.8.7`?

----

What version of kotlin do u use?

**Comment by anandpurushottam** [comment]
There is no specific reason to use jacoco version 0.8.7. Happy to use any compatible version.
Kotlin version: 1.9.10 is in use.
@SurpSG

**Comment by SurpSG** [comment]
@anandpurushottam could you please try to run with the latest jacoco?

**Comment by anandpurushottam** [comment]
<img width="506" alt="Screenshot 2024-01-19 at 12 59 13 AM" src="https://github.com/SurpSG/delta-coverage-plugin/assets/15199676/17d644ff-a31a-47e0-b3fb-7265fd4ea48d">

**Same result with jacoco version 0.8.11**
logs: 
https://gist.github.com/anandpurushottam/5f72ca2f0f2e52eafd14287e7019b4ec
@SurpSG

**Comment by SurpSG** [comment]
@anandpurushottam could you share please the source of the class. I need to debug it. 
For now I have no idea what is going on

**Comment by SurpSG** [comment]
@anandpurushottam 
By the way, you could try a new coverage engine instead of jacoco:
```
deltaCoverageReport {
    coverage {
        engine = CoverageEngine.INTELLIJ
   }
}
```

Also, get familiar how to configure [kover](https://github.com/Kotlin/kotlinx-kover) plugin.
Note: If you use `INTELLIJ` coverage then `coverageBinaryFiles` property must contain `*.ic` binary files generated by the kover plugin.
For more details see [parameters description](https://github.com/SurpSG/delta-coverage-plugin?tab=readme-ov-file#parameters-description)
