### ISSUE TITLE
BUG: Improve console report output

### ISSUE THREAD

**Issue by ajax-shapka-o** [SurpSG/delta-coverage-plugin#92]
1. Format line length
<img width="1719" alt="Screenshot 2024-02-28 at 18 49 28" src="https://github.com/SurpSG/delta-coverage-plugin/assets/113431234/1216d668-3913-4cd2-800e-35d4e149d91e">
2. Print report link at the end of the report

**Comment by SurpSG** [comment]
@ajax-shapka-o please check the latest version 2.2.0
